export const GET_MUSIC_LIST = 'GET_MUSIC_LIST';
export const GET_ARTIST = 'GET_ARTIST';
export const GET_TRENDING = 'GET_TRENDING';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const GET_MOVIE_VIDEO = 'GET_MOVIE_VIDEO';
export const GET_SIMILAR_MOVIE = 'GET_SIMILAR_MOVIE';
export const GET_MOVIE_TOP_RATED = 'GET_MOVIE_TOP_RATED';
export const GET_MOVIE_NOW_PLAYING = 'GET_MOVIE_NOW_PLAYING';
